name: Analyse OWASP avec Semgrep

on:
  push:
    branches: [main]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Analyse avec Semgrep et OWASP
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
