name: Analyse OWASP avec Semgrep

on:
  push:
    branches: [main]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installer Semgrep
        uses: returntocorp/semgrep-action@v1

      - name: Analyse avec les règles OWASP
        run: semgrep --config "p/owasp-top-ten" .