name: Node.js Package

on:
  push:                     # ✅ Ajouté pour exécuter à chaque push
    branches:
      - main                # ou 'develop' selon ta branche
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test       # ✅ Les tests unitaires sont lancés ici

  publish-npm:
    if: github.event_name == 'release'  # ✅ Ajouté pour éviter les déclenchements intempestifs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
